operators/src/engine/clonable_operator.rs, operators/src/engine/mod.rs, operators/src/engine/operator.rs, operators/src/engine/operator_impl.rs, operators/src/engine/result_descriptor.rs, operators/src/mock/mock_point_source.rs, operators/src/mock/mock_raster_point_join.rs, operators/src/mock/mock_raster_source.rs, operators/src/source/csv.rs, operators/src/source/gdal_source.rs, services/src/handlers/wms.rs, services/src/handlers/workflows.rs
this can also  hold tile size/resolution information for raster and fields for vector data
=> wrap type and projection of operators in a struct

services/Cargo.toml, services/src/bin/main.rs, services/src/error.rs, services/src/handlers/mod.rs, services/src/handlers/projects.rs, services/src/handlers/users.rs, services/src/handlers/wfs.rs, services/src/handlers/wms.rs, services/src/handlers/workflows.rs, services/src/server.rs, services/src/users/hashmap_userdb.rs, services/src/users/session.rs
makes service parameters more uniform and more easily extensible
=> refactor service parameters as context

datatypes/Cargo.toml, datatypes/src/collections/batch_builder.rs, datatypes/src/collections/data_types.rs, datatypes/src/collections/feature_collection.rs, datatypes/src/collections/multi_line_string_collection.rs, datatypes/src/collections/multi_polygon_collection.rs, operators/src/opencl/cl_program.rs, operators/src/opencl/mod.rs
Now, our OpenCL context allows us to use and create multi line and polygon collections.
=> OpenCL: Lines and Polygons

.github/workflows/ci.yml, .github/workflows/fix-nightly.yml
I tried out things here:
https://github.com/geo-engine/ci-tests/blob/main/.github/workflows/cargo.yml
That led to:
https://github.com/geo-engine/ci-tests/pull/1
=> Rust-Nightly autom. CI-Update

.github/workflows/ci.yml
- Fix a new Rust Nightly version
Auto-generated PR
=> Update Rust Nightly Version

dev.Dockerfile, docker/dev/service.sh
=> in docker run geoengine under different user to enable OpenCl

datatypes/src/primitives/time_step.rs, operators/src/engine/execution_context.rs, operators/src/engine/query.rs, operators/src/source/gdal_source.rs
=> fix time snap with interval month

operators/src/source/gdal_source.rs, services/src/contexts/in_memory.rs, services/src/contexts/mod.rs, services/src/contexts/postgres.rs, services/src/handlers/mod.rs, services/src/handlers/projects.rs, services/src/handlers/users.rs, services/src/handlers/wfs.rs, services/src/handlers/wms.rs, services/src/handlers/workflows.rs, services/src/users/session.rs
=> detach session from Context

operators/src/engine/execution_context.rs, operators/src/error.rs, operators/src/source/ogr_source.rs, services/src/contexts/mod.rs, services/src/datasets/in_memory.rs, services/src/datasets/listing.rs, services/src/datasets/postgres.rs, services/src/datasets/storage.rs, services/src/error.rs
=> Store data sets in memory and list them

Settings-default.toml, services/src/contexts/in_memory.rs, services/src/datasets/in_memory.rs, services/src/datasets/listing.rs, services/src/datasets/storage.rs, services/src/error.rs, services/src/handlers/datasets.rs, services/src/handlers/mod.rs, services/src/server.rs, services/src/util/config.rs, services/test.http
Please review it in conjunction with https://github.com/umr-dbs/wave/pull/98
https://trello.com/c/4xHXR84E
=> data set handler and changes to DataSet and DataSetDB

operators/src/engine/operator_impl.rs, operators/src/mock/mock_data_set_data_source.rs, operators/src/mock/mock_feature_collection_source.rs, operators/src/mock/mock_point_source.rs, operators/src/mock/mock_raster_point_join.rs, operators/src/mock/mock_raster_source.rs, operators/src/plot/histogram.rs, operators/src/plot/statistics.rs, operators/src/plot/temporal_raster_mean_plot.rs, operators/src/processing/column_range_filter.rs, operators/src/processing/expression.rs, operators/src/processing/point_in_polygon.rs, operators/src/processing/raster_vector_join/mod.rs, operators/src/processing/reprojection.rs, operators/src/processing/vector_join/mod.rs, operators/src/source/csv.rs, operators/src/source/ogr_source.rs
remove params from InitializedOperatorImpl
=> first step to a simple InitializedOperator

README.md, datatypes/src/primitives/time_interval.rs, services/src/ogc/util.rs
time parsing for values bc was not possible
=> Robust time parsing

operators/src/adapters/raster_overlap_adapter.rs
dont return before resetting the future
=> dont return before resetting the future

operators/src/adapters/sparse_tiles_fill_adapter.rs, operators/src/engine/operator_impl.rs, operators/src/lib.rs, operators/src/plot/box_plot.rs, operators/src/plot/scatter_plot.rs, operators/src/processing/meteosat/satellite.rs, operators/src/source/ogr_source.rs, operators/src/util/input/multi_raster_or_vector.rs, operators/src/util/raster_stream_to_geotiff.rs, operators/src/util/statistics.rs, services/src/datasets/external/pangaea/mod.rs, services/src/handlers/projects.rs, services/src/handlers/session.rs, services/src/handlers/workflows.rs, services/src/lib.rs, services/src/pro/contexts/postgres.rs, services/src/pro/handlers/projects.rs, services/src/pro/handlers/users.rs, services/src/pro/projects/hashmap_projectdb.rs
=> re-activate clíppy's semicolon lint wherever it is possible

operators/src/source/ogr_source/dataset_iterator.rs, operators/src/source/ogr_source/mod.rs
Allowing multiple attribute filters with multiple ranges;
=> Attribute filter fix

CHANGELOG.md, services/src/datasets/external/netcdfcf/error.rs, services/src/datasets/external/netcdfcf/gdalmd.rs, services/src/datasets/external/netcdfcf/mod.rs, services/src/datasets/external/netcdfcf/overviews.rs, services/src/handlers/ebv.rs, services/test.http
I basically look, if I can get a meaningful temporal resolution to create a regular time series like before.
If not, I use the metadata list that we created for Nature 4.0 to store a list of irregular timestamps with loading infos.
=> EBV provider loads non-regular data

.github/workflows/ci.yml, datatypes/src/operations/image/colorizer.rs, datatypes/src/operations/image/mod.rs, services/Cargo.toml, services/src/api/model/datatypes.rs, services/src/apidoc.rs, services/src/datasets/external/netcdfcf/ebvportal_provider.rs, services/src/datasets/external/netcdfcf/mod.rs, services/src/handlers/layers.rs, services/src/handlers/projects.rs, services/src/layers/layer.rs, services/src/layers/listing.rs, services/src/pro/apidoc.rs, services/src/pro/datasets/external/sentinel_s2_l2a_cogs.rs, services/src/projects/mod.rs, services/src/projects/project.rs, services/src/tasks/mod.rs, services/src/util/tests.rs
---
add docs for layer collection api
=> add docs for layer collection api

services/src/apidoc.rs, services/src/handlers/ebv.rs, services/src/pro/apidoc.rs, services/src/pro/server.rs, services/src/server.rs, services/src/util/apidoc.rs, services/src/util/server.rs
---
extend startup log and server info api
=> Server_info

services/src/pro/datasets/external/sentinel_s2_l2a_cogs.rs
=> retry gdal reads for STAC

.github/workflows/ci.yml, .github/workflows/clear-cache.yml
---
I added a dispatch action to clear the caches. We can then omit to increment random numbers in our CI.
I tested it here:
* https://github.com/geo-engine/cache-test/actions/runs/3265818610/attempts/1
* https://github.com/geo-engine/cache-test/actions/runs/3265818610/jobs/5368640698
=> clear cache action

services/src/handlers/layers.rs
=> wrong swagger ui placeholder

operators/src/processing/time_shift.rs
=> camelCase for TimeShift's timeInterval

operators/Cargo.toml, operators/src/error.rs, operators/src/pro/ml/mod.rs, services/Cargo.toml
=> put xgboost behind a feature

.github/workflows/ci.yml, .github/workflows/coverage.yml, services/Cargo.toml
=> update utoipa and utoipa swagger ui

bors.toml
=> disable coverage in bors for now

operators/src/adapters/sparse_tiles_fill_adapter.rs
=> handle edge case in fill adapter

services/src/handlers/ebv.rs, services/src/handlers/layers.rs
=> capture urlencoded params instead of arbitrary paths

datatypes/src/primitives/spatial_partition.rs, operators/src/plot/statistics.rs, operators/src/processing/raster_vector_join/aggregated.rs, operators/src/processing/raster_vector_join/non_aggregated.rs, services/src/handlers/plots.rs
---
i changed the polygon bounds to not wrap into the next tile
=> adapt bounds of polygon in test

services/src/api/model/datatypes.rs
=> add flatten to colorizer variants

services/src/api/model/datatypes.rs
=> more fixing on over/under colors in API

services/src/handlers/wcs.rs, services/src/handlers/wfs.rs, services/src/handlers/wms.rs
=> fix ogc capabilities url

CHANGELOG.md, services/src/datasets/external/gbif.rs, services/src/datasets/external/mod.rs, test_data/gbif/test_data.sql, test_data/provider_defs/nfdi/gbif.json
---
Add a provider for occurrence data points from gbif.org.
=> Gbif provider

services/src/pro/quota/mod.rs, services/src/pro/users/hashmap_userdb.rs
=> fix quota tracking in memory

services/src/pro/datasets/external/sentinel_s2_l2a_cogs.rs
=> fix s2 tests

operators/src/pro/ml/xgboost.rs
Fix code with respect to changes in the xgboost-rs crate.
=> fix: adapt code to changes in xgboost-rs crate

operators/src/util/raster_stream_to_geotiff.rs, services/src/handlers/wcs.rs, services/src/handlers/workflows.rs
=> raster stream to multiband tiff

services/src/handlers/layers.rs
=> return layer to workflow id as dict

services/src/layers/storage.rs, services/src/pro/contexts/postgres.rs
=> Fix-project-layer-bug

services/src/pro/contexts/postgres.rs, services/src/pro/projects/postgres_projectdb.rs, services/src/pro/util/tests.rs
=> change loading latest project version

services/src/pro/contexts/postgres.rs, services/src/pro/datasets/in_memory.rs, services/src/pro/permissions/in_memory_permissiondb.rs
=> remove permission check on dataset layer collection

services/src/datasets/external/gfbio_collections.rs, services/src/datasets/external/pangaea/mod.rs, services/src/error.rs
=> Hide GFBio collections item

operators/src/adapters/sparse_tiles_fill_adapter.rs, operators/src/processing/temporal_raster_aggregation/subquery.rs
=> temp aggregate should be valid for subquery window

Settings-default.toml, services/src/layers/layer.rs, services/src/util/config.rs
=> make layer list limit configurable

services/Cargo.toml, services/src/apidoc.rs, services/src/handlers/tasks.rs, services/src/pro/apidoc.rs, services/src/tasks/mod.rs, services/test.http
=> task fixes

.github/workflows/containers.yml
=> add action to post a message to slack on failure

services/src/pro/contexts/postgres.rs, services/src/pro/datasets/postgres.rs
=> Support more gdal metadata types in postgres

services/src/datasets/external/gbif.rs, services/src/error.rs
=> Include occurrence count in GBIF layer listing

operators/src/util/gdal.rs, services/benches/quota_check.rs, services/src/pro/handlers/permissions.rs, services/src/pro/util/tests.rs
=> assure that permissions are checked during operations init

operators/src/pro/cache/tile_cache.rs
=> calc cache entry size from bbox + tile in test

datatypes/src/dataset.rs, services/src/api/model/datatypes.rs, services/src/api/model/responses/datasets/mod.rs, services/src/apidoc.rs, services/src/datasets/create_from_workflow.rs, services/src/datasets/in_memory.rs, services/src/datasets/storage.rs, services/src/handlers/datasets.rs, services/src/handlers/layers.rs, services/src/handlers/wfs.rs, services/src/handlers/workflows.rs, services/src/pro/apidoc.rs, services/src/pro/contexts/postgres.rs, services/src/pro/datasets/add_from_directory.rs, services/src/pro/datasets/in_memory.rs, services/src/pro/datasets/postgres.rs, services/src/pro/handlers/datasets.rs, services/src/pro/handlers/drone_mapping.rs, services/src/pro/handlers/permissions.rs, services/src/pro/util/tests.rs, services/src/util/tests.rs
=> dataset names everywhere in dataset api

operators/src/processing/raster_vector_join/aggregated.rs, operators/src/processing/raster_vector_join/aggregator.rs, operators/src/processing/raster_vector_join/mod.rs, operators/src/processing/raster_vector_join/non_aggregated.rs, operators/src/processing/temporal_raster_aggregation/temporal_aggregation_operator.rs
=> ignore no data option for raster vector join

operators/src/engine/mod.rs, operators/src/engine/workflow_path.rs, operators/src/pro/adapters/stream_statistics_adapter.rs, operators/src/pro/meta/wrapper.rs, services/src/bin/main.rs
=> More_tracing

.github/workflows/coverage.yml
=> try to make space for coverage

datatypes/src/raster/empty_grid.rs, datatypes/src/raster/grid.rs, datatypes/src/raster/grid_or_empty.rs, datatypes/src/raster/masked_grid.rs, datatypes/src/raster/raster_properties.rs, datatypes/src/raster/raster_tile.rs, datatypes/src/util/byte_size.rs, datatypes/src/util/mod.rs, operators/src/pro/cache/tile_cache.rs
=> calculate grid bytes for cache entries

operators/src/processing/temporal_raster_aggregation/temporal_aggregation_operator.rs
=> set the return type of the raster agg

datatypes/src/spatial_reference.rs, operators/src/util/gdal.rs, services/src/datasets/external/netcdfcf/overviews.rs, services/src/handlers/ebv.rs
=> Esri-projections

services/src/datasets/external/gfbio_collections.rs, test_data/gfbio/collections_api_response.json
=> adjust gfbio collections data provider to new api

datatypes/src/primitives/bounding_box.rs, datatypes/src/primitives/spatial_partition.rs, datatypes/src/util/ranges.rs, operators/benches/cache_concurrent.rs, operators/src/engine/operator.rs, operators/src/engine/query_processor.rs, operators/src/pro/cache/cache_operator.rs, operators/src/pro/cache/error.rs, operators/src/pro/cache/tile_cache.rs, operators/src/util/raster_stream_to_geotiff.rs, operators/src/util/temporary_gdal_thread_local_config_options.rs, services/src/pro/server.rs
=> Tile-cache-cleanup

operators/src/processing/raster_vector_join/non_aggregated.rs
=> handle empty collections early in rastervectorjoin

Settings-default.toml, Settings-test.toml, operators/src/pro/adapters/stream_statistics_adapter.rs, operators/src/pro/meta/quota.rs, services/benches/quota_check.rs, services/src/pro/contexts/in_memory.rs, services/src/pro/contexts/mod.rs, services/src/pro/contexts/postgres.rs, services/src/pro/handlers/datasets.rs, services/src/pro/handlers/users.rs, services/src/pro/quota/mod.rs, services/src/pro/server.rs, services/src/pro/users/hashmap_userdb.rs, services/src/pro/users/postgres_userdb.rs, services/src/pro/util/config.rs
=> quota mode and update buffering

.github/workflows/coverage.yml
=> coverage on PR OR main branch push

services/src/pro/contexts/postgres.rs, services/src/pro/quota/mod.rs, services/src/pro/users/hashmap_userdb.rs, services/src/pro/users/postgres_userdb.rs, services/src/pro/users/userdb.rs
=> add bulk updates for quotas

services/src/layers/storage.rs, services/src/pro/layers/add_from_directory.rs
=> return properties if available

services/src/datasets/external/netcdfcf/mod.rs, services/src/datasets/external/netcdfcf/overviews.rs
=> cache-ttl in 4d provider

datatypes/src/primitives/time_instance.rs, services/src/api/model/datatypes.rs, services/src/api/model/db_types.rs, services/src/api/model/operators.rs, services/src/contexts/postgres.rs, services/src/contexts/schema.sql, services/src/datasets/postgres.rs, services/src/pro/datasets/postgres.rs
=> Pg-result-descriptor-mapping

services/src/contexts/schema.sql, services/src/layers/postgres_layer_db.rs, services/src/pro/layers/postgres_layer_db.rs
=> change type of workflow column in layers table

services/tests/startup.rs
=> kill process on startup test on errors

.github/workflows/containers.yml, datatypes/src/collections/feature_collection_builder.rs
=> Container-fix

Settings-default.toml, Settings-test.toml, services/src/handlers/ebv.rs, services/src/handlers/tasks.rs
=> remove remains of admin_session_token

services/src/pro/apidoc.rs, services/src/pro/contexts/postgres.rs, services/src/pro/handlers/users.rs, services/src/pro/permissions/mod.rs, services/src/pro/users/postgres_userdb.rs, services/src/pro/users/userdb.rs
---
- Added role descriptions endpoint to query role names for a logged in user.
=> Query role descriptions

services/src/contexts/postgres.rs, services/src/pro/server.rs, services/src/server.rs
---
- Added postgres port option to server startup.
=> Use postgres port on startup

README.md, Settings-default.toml, services/src/contexts/postgres.rs, services/src/error.rs, services/src/pro/server.rs, services/src/server.rs
=> change database schema

services/src/pro/contexts/postgres.rs, services/src/pro/datasets/postgres.rs, services/src/pro/layers/postgres_layer_db.rs, services/src/pro/permissions/mod.rs, services/src/pro/permissions/postgres_permissiondb.rs, services/src/pro/projects/postgres_projectdb.rs
=> check permissions in the same transaction as queries

services/src/datasets/postgres.rs, services/src/layers/postgres_layer_db.rs, services/src/pro/datasets/postgres.rs, services/src/pro/layers/postgres_layer_db.rs, services/src/pro/projects/postgres_projectdb.rs, services/src/projects/postgres_projectdb.rs, services/src/workflows/postgres_workflow_registry.rs
=> reuse queries in pro project db

datatypes/Cargo.toml
=> add array-impls to postgres-types

services/src/api/handlers/datasets.rs, services/src/datasets/postgres.rs, services/src/pro/datasets/postgres.rs, services/test.http
=> use options in list datasets

services/src/pro/api/apidoc.rs
=> added missing plot handler to pro api

services/src/datasets/external/edr.rs
=> relax edr test condition

Cargo.lock, services/Cargo.toml, services/src/api/apidoc.rs, services/src/pro/api/apidoc.rs, services/src/pro/api/handlers/users.rs, services/src/pro/users/mod.rs, services/src/pro/users/oidc.rs, services/src/projects/mod.rs, services/src/projects/project.rs
=> fix some openapi specs

operators/src/adapters/raster_stacker.rs, operators/src/processing/raster_stacker.rs
=> fix stacker adapter when streams are not immediately ready on poll

services/src/datasets/dataset_listing_provider.rs, services/src/datasets/listing.rs, services/src/datasets/postgres.rs, services/src/layers/external.rs, services/src/pro/datasets/postgres.rs
=> added search to dataset provider

datatypes/src/primitives/query_rectangle.rs, datatypes/src/raster/arrow_conversion.rs, services/src/api/apidoc.rs, services/src/api/handlers/workflows.rs, services/src/api/model/datatypes.rs, services/src/pro/api/apidoc.rs, services/src/util/parsing.rs
=> stream raster bands

services/src/datasets/external/gfbio_abcd.rs, test_data/gfbio/test_data.sql
=> Search for GFBio ABCD datasets

Cargo.lock, services/src/api/apidoc.rs, services/src/api/handlers/datasets.rs, services/src/api/model/responses/datasets/errors.rs, services/src/api/model/services.rs, services/src/datasets/postgres.rs, services/src/datasets/storage.rs, services/src/pro/api/apidoc.rs, services/src/pro/api/handlers/datasets.rs, services/src/pro/datasets/postgres.rs
=> make dataset info updatable

operators/src/adapters/raster_stacker.rs, operators/src/processing/time_shift.rs
=> fix bands in time shift

services/src/api/apidoc.rs, services/src/api/handlers/datasets.rs, services/src/api/model/services.rs, services/src/datasets/postgres.rs, services/src/datasets/storage.rs, services/src/pro/api/apidoc.rs, services/src/pro/api/handlers/datasets.rs, services/src/pro/datasets/postgres.rs
=> add tags to dataset update

services/src/api/handlers/datasets.rs, services/src/api/model/responses/datasets/errors.rs, services/src/datasets/postgres.rs, services/src/pro/api/handlers/datasets.rs, services/src/pro/datasets/postgres.rs, services/src/pro/users/postgres_userdb.rs, services/src/util/postgres.rs, services/test.http
=> check dataset name before insert

services/src/api/handlers/ebv.rs
=> add refresh route to swagger

services/src/contexts/migrations/migration_0008_band_names.rs
Use a paged (portal) query to prevent the migration from getting stuck
---
<TEXT>
=> Fix migration 0008

services/src/datasets/external/netcdfcf/error.rs, services/src/datasets/external/netcdfcf/overviews.rs
=> fix netcdf sref resolution when using overviews

operators/src/plot/statistics.rs
=> check initial sample for finite

services/src/pro/users/postgres_userdb.rs
---
Added missing attributes from users table from external_users table.
=> Missing attributes in session results

operators/src/processing/expression/mod.rs, operators/src/processing/expression/raster_operator.rs, operators/src/processing/expression/vector_operator.rs
=> bugfix: space in output_band of expression

.github/workflows/containers.yml
=> container test

services/src/api/handlers/layers.rs, services/src/api/handlers/workflows.rs, services/src/layers/postgres_layer_db.rs, services/src/pro/layers/postgres_layer_db.rs, services/src/pro/workflows/postgres_workflow_registry.rs, services/src/util/mod.rs, services/src/util/workflows.rs, services/src/workflows/postgres_workflow_registry.rs, services/src/workflows/registry.rs
=> layer workflows

Settings-default.toml, services/src/api/handlers/users.rs, services/src/config.rs, services/src/users/oidc.rs, services/src/util/tests.rs
=> Remove OIDC redirect URI

services/src/api/handlers/users.rs, services/src/users/oidc.rs
=> Add redirect URI to endpoints

services/src/contexts/migrations/database_migration.rs, services/src/contexts/migrations/mod.rs, services/src/contexts/migrations/schema_info.rs, services/src/datasets/external/edr.rs
=> make test more robust

operators/src/machine_learning/mod.rs, operators/src/machine_learning/onnx_util.rs
=> fix(operators): add empty onnx tensor shape to handled cases

Cargo.toml
=> build(services): update aruna

operators/src/processing/circle_merging_quadtree/operator.rs
BREAKING: it adds a new parameter `resolution` to visual clustering.
=> fix(operators): resolution in visual clustering

datatypes/src/primitives/time_interval.rs, datatypes/src/raster/tiling.rs, operators/src/util/raster_stream_to_geotiff.rs, services/src/api/handlers/layers.rs, services/src/api/handlers/workflows.rs, services/src/datasets/create_from_workflow.rs
---
added progress to dataset writer task
=> feat(services): add progress to dataset writer task
