services/src/contexts/postgres.rs, services/src/projects/hashmap_projectdb.rs, services/src/projects/postgres_projectdb.rs, services/src/projects/project.rs
I removed the check that versions must have a greater timestamp than the previous one because it causes tests to fail on my maschine because creation and update seem to happen at the same system time. The alternative would be to `sleep` shortly. However, as projects can be shared it's always possible two modifications happen at the same timestamp and that's ok as we shouldn't aim to solve phantom update problem here, as long as 
- the history is not lost
- there is only one true latest version of a project
this is both guaranteed for the postgres version
Another item to address: The `ProjectVersion` struct gets the local current time on `new` but the postgres item doesn't use this value but rather states `CURRENT_TIMESTAMP` and uses the database`s clock.
See: …
=> Project versions

datatypes/src/collections/multi_point_collection.rs, datatypes/src/operations/image/colorizer.rs, datatypes/src/plots/histogram.rs
as we always use the most recent nightly version of clippy, new PRs might fail with errors that have nothing to do with the branch but rather the master that now fails the CI. Maybe we could fix the clippy version to avoid this.
=> fix new clippy warnings

.github/workflows/ci.yml, .github/workflows/fix-nightly.yml, rust-toolchain
Currently, we fix the Rust version in our CI only. Now, we can fix this for our workspace. This means, when you execute `cargo`, `rustup` will automatically install the correct toolchain version for you.
=> Use `rust-toolchain` file to fix Rust version

.github/workflows/ci.yml, datatypes/src/spatial_reference.rs
build without postgres feature failed because ResultExt is required for .context() in `impl FromStr for SpatialReference {`
=> unbreak non postgres build

Settings-default.toml, Settings-test.toml, datatypes/src/raster/geo_transform.rs, datatypes/src/raster/mod.rs, datatypes/src/raster/raster_tile.rs, datatypes/src/raster/tiling.rs, operators/src/adapters/raster_time.rs, operators/src/engine/execution_context.rs, operators/src/source/gdal_source.rs, operators/src/source/mod.rs, services/src/handlers/wms.rs, services/src/util/config.rs
This PR
- moves TilingStrategy from GdalSource to Promitives.
- Adds a TilingSpecification to define origin and tile size
- Uses TilingSpecification in the ExecutionContext and generates a TilingStrategy for each query in the GdalSource
=> Global tiling spec

datatypes/src/collections/feature_collection.rs, datatypes/src/collections/geo_feature_collection.rs, datatypes/src/collections/multi_line_string_collection.rs, datatypes/src/collections/multi_point_collection.rs, datatypes/src/collections/multi_polygon_collection.rs, datatypes/src/operations/reproject.rs, datatypes/src/primitives/coordinate.rs, datatypes/src/primitives/multi_point.rs, datatypes/src/util/mod.rs, datatypes/src/util/well_known_data.rs, operators/src/processing/map_query.rs, operators/src/processing/mod.rs, operators/src/processing/query_rewrite.rs, operators/src/processing/reprojection.rs
This PR adds reprojection for FeatureCollections and introduces the Reprojection (Operator/Processor) and a MapQueryProcessor.
We can also replace the ReprojectionProcessor with a MapProcessor which takes a Fn(QueryRectangle> -> QueryRectangle and a Fn(G) -> G where G is the processed type. However, we can do this later.
=> handle_reprojection_part2

services/Cargo.toml, services/src/handlers/upload.rs, services/src/server.rs, services/src/util/config.rs
You can now override the configuration with environment variables.
An example:
```bash
GEOENGINE_WEB__EXTERNAL_ADDRESS=https://path.to.geoengine.io cargo run
```
You see that it worked on startup:
> [2021-11-24 13:42:41.000167 +01:00] INFO [geoengine_services::server] Starting server… https://path.to.geoengine.io/
=> Override config with environment variables

operators/benches/workflows.rs, operators/src/source/gdal_source/loading_info.rs, operators/src/source/gdal_source/mod.rs, operators/src/source/mod.rs, services/src/datasets/external/nature40.rs, services/src/datasets/external/netcdfcf/mod.rs, services/src/datasets/external/nfdi/mod.rs, services/src/pro/datasets/external/sentinel_s2_l2a_cogs.rs, services/src/pro/handlers/drone_mapping.rs
- refactor gdal source logic into specific methods
- rename GdalLoadingInfoPart into a more  descriptive name
- move SparseTileFill to run after all other steps are run
- swap "flatten" and "buffer" to buffer also when time slices change
=> refactor gdal source

services/src/datasets/external/gfbio.rs
Not using a plain SQL Query for retrieving ABCD datasets, since attribute filters do not get pushed down this way. Instead specified the unit table as layer-name and let OGR build the query string;
=> Allow pushdown of attribute filters in GFBio data provider

CHANGELOG.md, operators/src/processing/expression/parser.rs
---
Pest 2.4 deprecated PrecClimber for PrattParser. Since the functionality is equivalent, I adopted it to make it run through our CI again. PrecClimber would be removed in the future in any case.
=> pratt parser instead of prec climber

operators/src/source/gdal_source/mod.rs
---
changed the assert in gdal source where dataset pixel size and gdal pixelsize are compared into a warning. Somehow this is not always equal even if the number in the dataset is the number from gdalinfo.
=> warn not fail on gdal pixel size missmatch

Settings-default.toml
=> add GPX to default formats

services/src/pro/util/tests.rs
---
- Open ID Connect related tests failed, because the signing algorithm in the mock id token did not match the signing algorithm of the mock id provider.
=> Change signature algorithm of mock id token

operators/src/util/raster_stream_to_geotiff.rs
---
Filenames for different timesteps of exported datasets only had seconds in their filename. If a tilmestep had only differences in milliseconds, this caused errors.
=> Fix filename of exported dataset to support millisecond precision

services/src/contexts/mod.rs, services/src/pro/contexts/mod.rs
This PR is intended to fix a random error, where the tokio file writer sometimes hasn't actually finished, before the test reads the relevant content.
=> fix: add flush to tokio file writer in write_ml_model tests

services/src/datasets/external/gbif.rs
---
Column names were not put in quotation marks everywhere, so queries with column name "order" failed.
=> Gbif provider fix: Column names not in quotation marks

operators/src/source/gdal_source/mod.rs, operators/src/util/gdal.rs
=> enable gdal verbose errors in release build to detect file not found errors

services/src/pro/handlers/users.rs
=> add role id result type to open api spec

services/Cargo.toml
Quickfix for failing CI builds because of outdated dependency.
=> update tonic version: 0.8.3 -> 0.9

services/src/datasets/create_from_workflow.rs, services/src/handlers/layers.rs, services/src/handlers/workflows.rs
---
create dataset from worklfow now has the option to set a name for the new dataset
=> allow name for datasets from workflow

Settings-default.toml, services/src/bin/main.rs
---
- The file logging layer dropped the drop guard on creation. This causes the async file writer to drop also and results in empty log files.
- Additionaly, the log spec now uses EnvFilter which allows to use more complex filter e.g. per crate.
=> fix async file logger and more complex filters

services/src/projects/project.rs
LineSymbology was missing a camelCase such that auto_simplified could not be read properly.
=> LineSymbology Serialization Bug

services/src/api/handlers/datasets.rs, services/src/api/handlers/wms.rs, services/src/api/handlers/workflows.rs, services/src/contexts/mod.rs, services/src/contexts/postgres.rs, services/src/datasets/create_from_workflow.rs, services/src/datasets/listing.rs, services/src/datasets/postgres.rs, services/src/error.rs, services/src/pro/api/handlers/datasets.rs, services/src/pro/api/handlers/permissions.rs, services/src/pro/contexts/mod.rs, services/src/pro/contexts/postgres.rs, services/src/pro/datasets/postgres.rs
---
Added a check to layer_to_dataset / workflow_to_dataset that tests if a dataset name already exists. If the name is already in use an error is returned and no task is created.
=> check dataset name before task

services/src/datasets/external/netcdfcf/mod.rs
---
i changed the ticks of the default fallback colorizer
=> update fallback colorizer

services/src/api/handlers/datasets.rs, services/src/api/model/datatypes.rs, services/src/api/model/operators.rs, services/src/contexts/postgres.rs, services/src/datasets/external/gbif.rs, services/src/datasets/upload.rs, services/src/error.rs, services/src/pro/api/apidoc.rs, services/src/pro/api/handlers/datasets.rs, services/src/util/tests.rs
=> ajudst ogr time type to json format

operators/src/adapters/raster_subquery/raster_subquery_adapter.rs, operators/src/adapters/sparse_tiles_fill_adapter.rs, operators/src/mock/mock_raster_source.rs, operators/src/processing/reprojection.rs, operators/src/source/gdal_source/mod.rs, services/src/pro/datasets/external/sentinel_s2_l2a_cogs.rs
---
- Added requested time bounds to SparseTilesFillAdapter
- Adjust adapter to only fill in requested time ranges
- StacSentinel2Provider. clip times on full days to avoid wrong aggregations
=> SparseTilesFillAdapter: add requested bounds, fill only if needed

.github/workflows/ci.yml, .scripts/check-expression-deps.rs, README.md
=> verify expression deps

services/src/api/model/datatypes.rs
=> fix(services): classification measurement serialization

datatypes/src/operations/reproject.rs, datatypes/src/primitives/bounding_box.rs, datatypes/src/primitives/spatial_partition.rs, operators/src/processing/reprojection.rs, services/src/api/handlers/plots.rs
Combines clipped and non-clipped reprojection of border sample points. The largest possible bbox (a combination of both or the one which is non-empty) is taken as result.
---
<TEXT>
=> feat(datatypes): reproject outside area of use
